; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

include listing.inc

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?AsInt@GameEntity@@QEBAHXZ			; GameEntity::AsInt
PUBLIC	probe
;	COMDAT pdata
pdata	SEGMENT
$pdata$probe DD	imagerel $LN6
	DD	imagerel $LN6+21
	DD	imagerel $unwind$probe
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$probe DD 010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\micha\AppData\Local\Temp\xmod-omnibot-abi-20260923\probe.cpp
;	COMDAT probe
_TEXT	SEGMENT
p$ = 48
$T1 = 48
probe	PROC						; COMDAT

; 48   : extern "C" int probe(Probe *p) { return p->GetLocalGameEntity().AsInt(); }

$LN6:
	sub	rsp, 40					; 00000028H
	mov	rax, QWORD PTR [rcx]
	lea	rdx, QWORD PTR $T1[rsp]
	call	QWORD PTR [rax]
	mov	eax, DWORD PTR [rax]
	add	rsp, 40					; 00000028H
	ret	0
probe	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\micha\AppData\Local\Temp\xmod-omnibot-abi-20260923\probe.cpp
;	COMDAT ?AsInt@GameEntity@@QEBAHXZ
_TEXT	SEGMENT
this$ = 8
?AsInt@GameEntity@@QEBAHXZ PROC				; GameEntity::AsInt, COMDAT

; 8    : 	obint32 AsInt() const { return udata.m_Int; }

	mov	eax, DWORD PTR [rcx]
	ret	0
?AsInt@GameEntity@@QEBAHXZ ENDP				; GameEntity::AsInt
_TEXT	ENDS
END
