; Listing generated by Microsoft (R) Optimizing Compiler Version 19.44.35222.0 

	TITLE	C:\Users\micha\AppData\Local\Temp\xmod-omnibot-abi-20260923\msvc32.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?AsInt@GameEntity@@QBEHXZ			; GameEntity::AsInt
PUBLIC	_probe
; Function compile flags: /Ogtpy
; File C:\Users\micha\AppData\Local\Temp\xmod-omnibot-abi-20260923\probe.cpp
;	COMDAT _probe
_TEXT	SEGMENT
_p$ = 8							; size = 4
$T1 = 8							; size = 4
_probe	PROC						; COMDAT

; 48   : extern "C" int probe(Probe *p) { return p->GetLocalGameEntity().AsInt(); }

	mov	ecx, DWORD PTR _p$[esp-4]
	lea	edx, DWORD PTR $T1[esp-4]
	push	edx
	mov	eax, DWORD PTR [ecx]
	call	DWORD PTR [eax]
	mov	eax, DWORD PTR [eax]
	ret	0
_probe	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File C:\Users\micha\AppData\Local\Temp\xmod-omnibot-abi-20260923\probe.cpp
;	COMDAT ?AsInt@GameEntity@@QBEHXZ
_TEXT	SEGMENT
?AsInt@GameEntity@@QBEHXZ PROC				; GameEntity::AsInt, COMDAT
; _this$ = ecx

; 8    : 	obint32 AsInt() const { return udata.m_Int; }

	mov	eax, DWORD PTR [ecx]
	ret	0
?AsInt@GameEntity@@QBEHXZ ENDP				; GameEntity::AsInt
_TEXT	ENDS
END
