#ifndef BASE_PROJECT_H
#define BASE_PROJECT_H

///////////////////////////////////////////////////////////////////////////////
// Auto-generated project configuration header
// This file provides default values for Visual Studio builds.
// For GNUmakefile builds, this file is generated by project/info.py
///////////////////////////////////////////////////////////////////////////////

// Only define if not already defined (allows makefile to override)
#ifndef XMOD_name

#define XMOD_name           "xmod"
#define XMOD_namef          "xmod"
#define XMOD_namex          "^xxmod"
#define XMOD_website        "https://github.com/jay1110/xmod"
#define XMOD_irc            ""
#define XMOD_author         "Jaybird, ETc|#.Jay.#"
#define XMOD_copyright      "Copyright (c) 2005-2011 Jaybird, 2025 jay1110. All Rights Reserved."
#define XMOD_versionMajor   "2"
#define XMOD_versionMinor   "0"
#define XMOD_versionPoint   "0"
#define XMOD_versionHex     0x02000000
#define XMOD_buildDate      __DATE__ " " __TIME__
#define XMOD_buildStability "development"
#define XMOD_buildTarget    "windows"
#define XMOD_repoURL        ""
#define XMOD_repoUUID       "git"
#define XMOD_repoRev        "unknown"
#define XMOD_repoLCRev      "unknown"
#define XMOD_repoLCDate     ""
#define XMOD_platformName   "Windows"
#define XMOD_platformNamef  "windows"
#define XMOD_title          "xmod 2.0.0"
#define XMOD_titlex         "^xxmod ^f2.0.0"
#define XMOD_version        "2.0.0"
#define XMOD_versionx       "^f2.0.0"
#define XMOD_packageBase    "xmod-2.0.0"
#define XMOD_packageBasev   "xmod-2.0.0-windows"
#define XMOD_pk3            "xmod-2.0.0.pk3"

#endif // XMOD_name

///////////////////////////////////////////////////////////////////////////////
// Platform detection for Visual Studio builds
///////////////////////////////////////////////////////////////////////////////

#if defined(_WIN32) || defined(_WIN64)
#  ifndef XMOD_WINDOWS
#    ifdef _WIN64
#      define XMOD_WINDOWS64
#    else
#      define XMOD_WINDOWS
#    endif
#  endif
#endif

#ifndef XMOD_DEVELOPMENT
#  define XMOD_DEVELOPMENT
#endif

///////////////////////////////////////////////////////////////////////////////

#endif // BASE_PROJECT_H
